
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: NGINX
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./djangoapp/{{cookiecutter.project_name}}:/djangoapp/{{cookiecutter.project_name}}
      - ./config/nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
      - ./static:/static
      - ./media:/media
    depends_on:
      - app
  app:
    build: .
    container_name: DJANGO
    command: bash -c "./wait-for-it.sh db:5432 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn {{cookiecutter.project_name}}.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./djangoapp/{{cookiecutter.project_name}}:/djangoapp/{{cookiecutter.project_name}}
      - ./static:/static
      - ./media:/media
    expose:
      - "8000"
    env_file:
      - ./config/djangoapp.env
  db:
    image: postgres:latest
    container_name: POSTGRES
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./config/database.env
